name: mental_health_partner
description: A mental health companion application

# Prevents accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Network and API
  dio: ^5.3.2
  json_annotation: ^4.9.0
  # Local storage
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  # UI components
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  # Charts for mood tracking
  fl_chart: ^0.71.0
  # Animation
  lottie: ^2.6.0
  # Utils
  logger: ^2.0.2
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.1
  # Form validation
  formz: ^0.6.1

  dartz: ^0.10.1
  path: any
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300